export enum CANDIDATE_SOURCE {
	UPLOAD = 'UPLOAD',
	LINKEDIN = 'LINKEDIN',
	REFERRAL = 'REFERRAL',
	OTHER = 'OTHER',
}

export enum APPLICATION_STATUS {
	ACTIVE = 'ACTIVE',
	REJECTED = 'REJECTED',
	WITHDRAWN = 'WITHDRAWN',
	HIRED = 'HIRED',
}
